Repository eludris-community/evangeline, pull requests merged in 2022-12, with the labels that each got.

#5 ci: add release-please
  .github/workflows/release-please.yml
Labels: p: low, t: ci

#7 fix: make evangeline work... I think
  .gitignore
  README.md
  lib/bot.ts
  lib/index.ts
  lib/types/index.d.ts
  lib/types/message.ts
  package.json
  src/lib/index.ts
  tsconfig.json
Labels: p: high, t: fix

#3 chore: create a documentation
  lib/bot.ts
  lib/index.ts
  lib/types/message.ts
  package.json
  typedoc.json
Labels: p: medium, t: docs
